[ids]
# Please replace the keyboard ID by checking `sudo keyd monitor`
*
04f3:3230:66f0738f

[main]
capslock = layer(fn_layer_2)

enter = overload(alt, enter)

z = overload(control, z)
x = overload(alt, x)
slash = overload(meta, slash)

# f20 is used for henkan in this file.
space = overloadt(fn_layer_1, space, 200)
rightalt = overload(control, f20)
rightcontrol = leftalt

[fn_layer_1]
# First Row
grave = esc
1 = noop
2 = f2
3 = noop
4 = noop
5 = noop
6 = noop
7 = noop
8 = noop
9 = noop
0 = noop
minus = noop
equal = f12
# Pass through: backspace

# Second Row
tab = grave
q = 1
w = 2
e = 3
r = 4
t = 5
y = 6
u = 7
i = 8
o = 9
p = 0
leftbrace = minus
rightbrace = equal
backslash = backspace

# Third Row
capslock = layer(fn_layer_2)
a = noop
s = noop
d = (
f = )
g = noop
h = noop
j = [
k = ]
l = noop
# Pass through: semicolon, apostrophe, enter

# Fourth Row
z = noop
x = noop
c = noop
v = noop
b = noop
n = noop
m = noop
# Pass through: leftshift, comma, dot, slash, rightshift

# Fifth Row
# All Pass through

[fn_layer_2]
# NOTE: Enable an option to enable numpad to operate mouse keys.
# Plus, tweak mouse speed:
# $ gsettings set org.gnome.desktop.a11y.keyboard mousekeys-accel-time 0
# $ gsettings set org.gnome.desktop.a11y.keyboard mousekeys-init-delay 0
# s set org.gnome.desktop.a11y.keyboard mousekeys-max-speed 200

# First Row
grave = esc
1 = C-1
2 = C-2
3 = C-3
4 = C-4
5 = C-5
6 = C-6
7 = C-7
8 = C-8
9 = C-9
0 = noop
minus = C-minus
equal = C-equal
# Pass through: backspace

# Second Row
tab = C-tab
q = leftmeta
w = leftmouse
e = kp8
r = rightmouse
t = scrollup
y = C-y
u = home
i = up
o = end
p = backspace
leftbrace = pageup
rightbrace = A-left
backslash = A-right

# Third Row
a = leftshift
s = kp4
d = kp2
f = kp6
g = scrolldown
h = leftmouse
j = left
k = down
l = right
semicolon = esc
apostrophe = pagedown
# Pass through: enter

# Fourth Row
leftshift = noop
z = C-z
x = C-x
c = C-c
v = C-v
b = C-b
n = noop
m = noop
comma = noop
dot = noop
slash = delete
rightshift = backspace

# Fifth Row
leftcontrol = noop
leftmeta = noop
leftalt = noop
space = leftcontrol
rightalt = leftalt
rightcontrol = noop
left = noop
right = noop
up = noop
down = noop
